---
name: Build Releases
on: push

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Cache Python modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.pip
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.5.0
          virtualenvs-create: false
          installer-parallel: true

      - name: Install Python Dependencies
        run: C:\Users\runneradmin\.local\bin\poetry install --no-interaction --no-ansi
        env:
          PIP_CACHE_DIR: ~/.pip

      - name: Build Executable
        run: C:\Users\runneradmin\.local\bin\poetry run pyinstaller --onefile hstsparser.py

      - name: Print Helptext to Validate Executable
        run: dist\hstsparser.exe

      - name: Upload Executable
        uses: actions/upload-artifact@v3
        with:
          name: hstsparser.exe
          path: dist/hstsparser.exe
