---
name: Build Releases
on: push

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Cache Python modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.pip
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.5.0
          virtualenvs-create: false
          installer-parallel: true

      - name: Install Python Dependencies
        run: C:\Users\runneradmin\.local\bin\poetry install --no-interaction --no-ansi --without=dev
        env:
          PIP_CACHE_DIR: ~/.pip

      - name: Build Executable
        run: C:\Users\runneradmin\.local\bin\poetry run pyinstaller --onefile --additional-hooks-dir hooks hstsparser.py

      - name: Print Helptext to Validate Executable
        run: dist\hstsparser.exe -h

      - name: Upload Executable
        uses: actions/upload-artifact@v3
        with:
          name: hstsparser.exe
          path: dist/hstsparser.exe

  rpm:
    runs-on: ubuntu-latest
    container:
      image: docker.io/library/fedora:38
      options: "--privileged"

    steps:
      - name: Install Git
        run: dnf install git -y

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: dnf install rpmdevtools rpm-build make tar dnf-plugins-core -y

      - name: Build SRPM
        run: make srpm

      - name: Build RPM in Mock
        uses: mmornati/docker-mock-rpmbuilder@master
        env:
          SPEC_FILE: "hstsparser.spec"
          SOURCES: "rpmbuild/SOURCES/hstsparser-1.1.8.tar.gz"
          MOCK_CONFIG: "fedora-38-x86_64"
          MOUNT_POINT: "${GITHUB_WORKSPACE}"

      - name: Upload SRPM
        uses: actions/upload-artifact@v3
        with:
          name: hstsparser-1.1.8-3.fc38.src.rpm
          path: rpmbuild/SRPMS/hstsparser-1.1.8-3.fc38.src.rpm
          if-no-files-found: error

      - name: Upload RPM
        uses: actions/upload-artifact@v3
        with:
          name: hstsparser-1.1.8-3.fc38.noarch.rpm
          path: rpmbuild/output/hstsparser-1.1.8-3.fc38.noarch.rpm
          if-no-files-found: error
