---
name: Publish Releases
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: "Semver to release"

jobs:
  github:
    runs-on: ubuntu-latest
    steps:
      - name: Download Windows Release
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yaml
          commit: ${{github.event.pull_request.head.sha}}
          name: hstsparser.exe

      - name: Create Draft GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          tag_name: ${{inputs.version}}
          generate_release_notes: true
          files: |
            hstsparser.exe